artifact_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1JVnAlKEgAsle2tRMmJ0IfGnm7a-cy7YE/view?usp=sharing
  local_data_files: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


# For the prepration base model : 2nd stage

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pth
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pth


# For the training : 3rd stage

training:
  root_dir: artifacts/training
  training_model_path: artifacts/training/model.pth


